services:
  api:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PedidosDb;User=sa;Password=Altamir123@;Encrypt=False;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Altamir123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped